from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum

# Define the exactly 4 allowed Personas
class PersonaType(str, Enum):
    FIRST_STEPPER = "First Stepper"
    CHOICE_MAKER = "Choice Maker"
    FUTURE_BUILDER = "Future Builder"
    U_TURN = "Problem Solver (U-Turn)"

# 1. Frontend -> Backend: The initial payload from the user
class AssessmentPayload(BaseModel):
    user_id: Optional[str] = None # Nullable for guest users
    persona: PersonaType
    raw_answers: List[str] = Field(description="The raw answers from the Potential Prism or Choice Maker")
    current_job: Optional[str] = Field(None, description="Only required if U-Turn persona")

# 2. AI -> Backend -> Frontend: The structured psychological draft
class UserDraft(BaseModel):
    core_traits: List[str] = Field(description="Read-only psychological traits generated by AI")
    hard_skills: List[str] = Field(description="Editable list of technical skills")
    interests: List[str] = Field(description="Editable list of sectors or job interests")
    constraints: List[str] = Field(description="Editable list of user limitations (e.g., 'no coding')")

# 3. Frontend -> Backend: User sends the edited draft back to find jobs
class DraftApprovalPayload(BaseModel):
    user_id: Optional[str] = None
    approved_draft: UserDraft

# 4. Backend -> Frontend: The final roadmap
class RoadmapWeek(BaseModel):
    week_number: int
    focus_area: str
    action_items: List[str]

class FinalRoadmap(BaseModel):
    target_role: str
    estimated_weeks: int
    timeline: List[RoadmapWeek]

class QAPair(BaseModel):
    question: str
    answer: str

class PrismStepRequest(BaseModel):
    user_id: Optional[str] = None
    persona: PersonaType
    history: List[QAPair] = Field(
        default_factory=list, 
        description="The chat history of questions already asked and answered"
    )

class UserDraft(BaseModel):
    core_traits: List[str]
    hard_skills: List[str]
    interests: List[str]
    constraints: List[str]

class PrismStepResponse(BaseModel):
    is_complete: bool = Field(description="True if the AI has enough data to finish the assessment")
    question_text: Optional[str] = Field(None, description="The next question to ask the user")
    visual_tag: Optional[str] = Field(None, description="The semantic tag for the Next.js UI to load the Lottie animation")
    final_draft: Optional[UserDraft] = Field(None, description="Populated only if is_complete is True")        